---
- name: installs ruby
  yum: name=ruby

- name: installs test-kitchen
  gem: name=test-kitchen version={{ kitchen_version }} user_install=no

- name: installs kitchen ansible
  gem: name=kitchen-ansible version={{ kitchen_ansible_version }} user_install=no